### ISSUE TITLE
Gantt Doesn't work at all

### ISSUE THREAD

**Issue by ismaelbonato** [wekan/wekan-gantt-gpl#1]
Hello, I tried the docker and snap version but both give me blank screen, it can be a bug or me, because I don't know how to use Wekan yet.

I've attached 2 pictures if it can help someone.

![photo1](https://user-images.githubusercontent.com/7233514/108123732-11693180-7085-11eb-8f6a-f835179e0633.png)
![photo2](https://user-images.githubusercontent.com/7233514/108123785-25149800-7085-11eb-8591-e9e34221e9e0.png)

**Comment by xet7** [comment]
At cards, both Start and End dates should be set (not Due date) for the tasks to be displayed.

https://github.com/wekan/wekan/wiki/Gantt
