### ISSUE TITLE
the tag for v5.07 points to the wrong commit

### ISSUE THREAD

**Issue by r0one** [wekan/wekan-gantt-gpl#2]
Hi there!

It looks like the git tag for release v5.07 points to df54863e7243b0b067ec2d30d8352ff1838931c4 which does nothing (except changing some metadata). It should probably point to the fd0939b5b89f70ae3bd782cff2e0e415fbf68cc4 commit which pulls changes from the MIT upstream.

As no docker tags (except latest) are pushed on docker hub, I have to build wekan-gantt docker images manually (by pulling the docker repo) and it would be nice to be able to set which release I'm pulling using tags, like on docker hub.

**Comment by xet7** [comment]
@R0one 

That is only problem with Docker Hub. I try to figure out can I get Docker Hub tags working.

Quay works: https://quay.io/wekan/wekan-gantt-gpl
```
image: quay.io/wekan/wekan-gantt-gpl:v5.07
```
