### ISSUE TITLE
Gantt Diagram Link to Wekan card is broken  - Board not found

### ISSUE THREAD

**Issue by julred** [wekan/wekan-gantt-gpl#21]
## Issue
All my open tasks are perfectly shown in the gantt diagram. But when I click on a task inside the gantt diagram, I exepct Wekan shall open the task description. But I get the feedback, that 'Board was not found'. So the link is somehow broken.

### Server Setup Information
* Did you test in newest Wekan?: V6.09.0
* Did you configure root-url correctly: yes (running Wekan inside VMware with port forwarding)
* Operating System: Ubuntu Server 22.04
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Snap
* Node.js Version: 12.22.10
* MongoDB Version: 3.2.22
* What webbrowser version are you using: Chrome

#### Reproduction Steps

![wekan_issue](https://user-images.githubusercontent.com/6383396/215736606-921563c1-9052-4dfd-8d2e-7ffb0563c705.gif)

**Comment by MeriemBH** [comment]
Hello,

i have the same error.
What did you to solve it?

thanks

**Comment by julred** [comment]
I did not resolved it - I switched to "normal" Wekan without Gantt functionality.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2870#issuecomment-1267020057
