### ISSUE TITLE
wekan_gantt on windows

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan-gantt-gpl#26]
Hello,

i installed wekan on ubunto using snap and it worked fine.
Now , i want to install it on windows without being dependent to the net.
the link [https://github.com/wekan/wekan/wiki/Offline] is not clear enough.
thanks,

**Comment by xet7** [comment]
@MeriemBH 

Sorry. I fixed links. Try again:

a) at https://github.com/wekan/wekan/wiki/Offline

**Comment by MeriemBH** [comment]
i will try the new link. Can i use windows 8 instead of 22?

**Comment by MeriemBH** [comment]
@xet7  the file node-v14.21.4-win-x64.exe can endomage the computer and i can not find this version in the official site of node.

**Comment by xet7** [comment]
@MeriemBH 

Node.js 14.21.4 is safe version maintained by Meteor, not by original Node.js developers, that is why it is at different website. Source code etc info at https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4

If Windows 8 is 64bit version, maybe it works, but I have not tested at Windows 8 64bit. It does not work at Windows 8 32bit. I also have not yet tested does MongoDB work on Windows 8.

**Comment by xet7** [comment]
@MeriemBH 

Windows 8 is EOL January 2023. It does not receive security updates anymore, it is not safe to use.

https://learn.microsoft.com/en-us/lifecycle/products/windows-81

I recommed installing newest Ubuntu 23.10 64bit and from app store GUI installing WeKan Snap Candidate, it is newest.

**Comment by xet7** [comment]
Ubuntu 23.10 also has newest Linux Kernel 6.5 that has newest security fixes.
