### ISSUE TITLE
the tag for v5.08 points to the wrong commit

### ISSUE THREAD

**Issue by r0one** [wekan/wekan-gantt-gpl#3]
Hi!

tag v5.08 points to c9830bc262c0ff109a7721e34f5fb6887de0d858. Shouldn't it point to f9d4f294fd6b509b1505945cd44b912f57793aa3 instead?

**Comment by xet7** [comment]
@R0one 

Maybe. Currently this happens:

1. First I release [wekan](https://github.com/wekan/wekan) version and add release tag https://github.com/wekan/wekan-gantt-gpl/commit/c9830bc262c0ff109a7721e34f5fb6887de0d858 here https://github.com/wekan/wekan/blob/master/releases/release.sh#L10 that also build bundle and Sandstorm versions in release.sh script.
2. Then I merge [wekan/wekan](https://github.com/wekan/wekan/wekan) to [wekan/wekan-ondra](https://github.com/wekan/wekan/wekan-ondra) and [wekan/wekan-gantt-gpl](https://github.com/wekan/wekan/wekan-gantt-gpl) repos with this same script https://github.com/wekan/wekan/blob/master/releases/release-ondra-1.sh#L2 and push changes with https://github.com/wekan/wekan/blob/master/releases/release-ondra-2.sh
3. After that I build [Snap packages](https://github.com/wekan/wekan-snap/wiki/Making-releases) for [wekan](https://snapcraft.io/wekan), [wekan-ondra](https://snapcraft.io/wekan-ondra) and [wekan-gantt-gpl](https://snapcraft.io/wekan-gantt-gpl).
4. [Docker wekan-gantt-gpl](https://quay.io/wekan/wekan-gantt-gpl) is built automatically from tags.

I'm thinking, could it be possible to move tag with some commands, or should I just create new tag like v5.08-gantt ?

**Comment by r0one** [comment]
I think the whole issue is that tagging should occur *after* having merged the MIT upstream ([wekan/wekan](https://github.com/wekan/wekan/wekan)) in the other repos.

> I'm thinking, could it be possible to move tag with some commands?

Yeah, totally, you could force a pre-existing tag to point to something else, like this:

```bash
git tag --force v5.08 f9d4f294fd6b509b1505945cd44b912f57793aa3
```
or
```bash
git tag --force v5.08 HEAD
```
It might be a bit dangerous, if you're not sure that the merging has been done, so I would recommend doing that in [release-ondra-1.sh](https://github.com/wekan/wekan/blob/master/releases/release-ondra-1.sh#L2), right after the merge.

> or should I just create new tag like v5.08-gantt ?

That's another option, but it would create some mess: the repo would contain both the vX.XX-gantt tags, and the vX.XX tags merged from the upstream.

**Comment by xet7** [comment]
Ok, I tried this for gantt and ondra:
```
git tag --force v5.08 GIT-HASH-HERE
git push --tags --force
```
I'll try building Snap and Docker for gantt and ondra again.

**Comment by r0one** [comment]
Works for me!

**Comment by r0one** [comment]
As for your release workflow, maybe you should find a way to pass the release number as an argument to release-ondra.sh, so that it looks like this:
```bash
git fetch upstream
git merge upstream/master
git tag --force "$1" HEAD
```

**Comment by xet7** [comment]
@R0one 

Thanks, I'll try that!

**Comment by r0one** [comment]
I've also tested v5.13 and it is fine for me! I guess I can close this issue. Again, thanks!
