### ISSUE TITLE
Docker image on quay.io not up to date

### ISSUE THREAD

**Issue by rdelaage** [wekan/wekan-gantt-gpl#34]
The latest image published on quay.io is v7.10 but the latest release on https://github.com/wekan/wekan is v7.24. The MIT version of wekan seems up to date

**Comment by xet7** [comment]
@rdelaage 

Gantt feature was very limited, and Gantt Chart component had GPL license, so WeKan Gantt version has been discontinued.

There will be added MIT licensed Gantt to MIT WeKan https://github.com/wekan/wekan/issues/2870#issuecomment-1516992963
