### ISSUE TITLE
Gantt does not exist 

### ISSUE THREAD

**Issue by smhl1989** [wekan/wekan-gantt-gpl#5]
## Issue
When I try to switch from the swim lane chart to the Gantt chart and click on the card to preview the content of the card, an error page appears that the board does not exist 

If you exit the Kanban board, reload and switch to the Gantt chart at this time, the problem will be temporarily hidden, but if you switch the view again, the problem will reappear 

Sorry, I really don’t have a clue, how can I deal with this problem? 

By the way, how do I query and export logs? Does it only support temporary queries like snap logs wekan-gantt-gpl? Are there other documents or operations?

**Comment by xet7** [comment]
@smhl1989 

Here is how to use Gantt feature: https://github.com/wekan/wekan/wiki/Gantt 

Logs at snap:
```
sudo snap logs wekan-gantt-gpl.wekan
```
Or alternatively, look at your `/var/log/syslog`

Does these help?

**Comment by julred** [comment]
Same issue as issue #21

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2870#issuecomment-1267020057
