### ISSUE TITLE
Issue with Gantt view

### ISSUE THREAD

**Issue by killmasta93** [wekan/wekan-gantt-gpl#7]
HI
Currently trying to install the wekan with gantt, but there is an issue with the grantt view when i click on the view it shows in grey

![image](https://user-images.githubusercontent.com/13953629/177017282-35404285-b2a8-47e2-ac9c-a38b31875e58.png)

this part of the log is the only thing i see

Currently running docker-compose,yml file default 
```
wekan-app  | {"line":"87","file":"percolate_synced-cron.js","message":"SyncedCron: Scheduled \"notification_cleanup\" next run @Sat Jul 02 2022 21:59:35 GMT+0000 (Coordinated Universal Time)","time":{"$date":1656799176456},"level":"info"}
wekan-app  | (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
wekan-app  | (Use `node --trace-deprecation ...` to show where the warning was created)
```
Thank you

**Comment by xet7** [comment]
@killmasta93 

Did you add some dates?

From https://github.com/wekan/wekan/wiki/Gantt#how-to-use

> At cards, both Start and End dates should be set (not Due date) for the tasks to be displayed.

**Comment by xet7** [comment]
When I tried it, it seems there is only slider, but not Gantt chart. Maybe it's some bug, or some code is missing.

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan/issues/2870

**Comment by killmasta93** [comment]
thanks for the reply correct this is what i have so far
![image](https://user-images.githubusercontent.com/13953629/177018300-1f7c6165-a2de-4dfa-ac05-b3d750305caa.png)

**Comment by killmasta93** [comment]
so its seems to be a bug on the gantt view?

**Comment by xet7** [comment]
@killmasta93 

Yes.

**Comment by killmasta93** [comment]
thanks for the reply, any future updates for this fix?

**Comment by xet7** [comment]
@killmasta93 

Depends does someone help figuring this out. There are also other stuff to fix.

**Comment by killmasta93** [comment]
is there something i can do to help? or to troubleshoot

**Comment by xet7** [comment]
@killmasta93 

Yes. Look is all Gantt related code in WeKan:
- https://github.com/wekan/wekan/issues/2870#issuecomment-694998553
- https://github.com/wekan/wekan/wiki/Gantt
- https://github.com/wekan/wekan-gantt-gpl

**Comment by xet7** [comment]
Also anything gantt related at https://github.com/wekan/wekan-gantt-gpl/blob/master/CHANGELOG.md

**Comment by g-giordano** [comment]
Hi,
I have the same error, gantt is not shown.
Can you help me?
tks

**Comment by g-giordano** [comment]
Is it a bug?
Any idea?
Tks

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/2870#issuecomment-1267020057
